package com.vmax.entity;

import java.io.Serializable;
import java.util.Date;

public class Tbpermission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpermission.lId
     *
     * @mbggenerated
     */
    private Long lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpermission.strPermission
     *
     * @mbggenerated
     */
    private String strpermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpermission.strDescription
     *
     * @mbggenerated
     */
    private String strdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpermission.nState
     *
     * @mbggenerated
     */
    private Integer nstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpermission.dtCreateTime
     *
     * @mbggenerated
     */
    private Date dtcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbpermission.dtModifyTime
     *
     * @mbggenerated
     */
    private Date dtmodifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbpermission
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpermission.lId
     *
     * @return the value of tbpermission.lId
     *
     * @mbggenerated
     */
    public Long getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpermission.lId
     *
     * @param lid the value for tbpermission.lId
     *
     * @mbggenerated
     */
    public void setLid(Long lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpermission.strPermission
     *
     * @return the value of tbpermission.strPermission
     *
     * @mbggenerated
     */
    public String getStrpermission() {
        return strpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpermission.strPermission
     *
     * @param strpermission the value for tbpermission.strPermission
     *
     * @mbggenerated
     */
    public void setStrpermission(String strpermission) {
        this.strpermission = strpermission == null ? null : strpermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpermission.strDescription
     *
     * @return the value of tbpermission.strDescription
     *
     * @mbggenerated
     */
    public String getStrdescription() {
        return strdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpermission.strDescription
     *
     * @param strdescription the value for tbpermission.strDescription
     *
     * @mbggenerated
     */
    public void setStrdescription(String strdescription) {
        this.strdescription = strdescription == null ? null : strdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpermission.nState
     *
     * @return the value of tbpermission.nState
     *
     * @mbggenerated
     */
    public Integer getNstate() {
        return nstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpermission.nState
     *
     * @param nstate the value for tbpermission.nState
     *
     * @mbggenerated
     */
    public void setNstate(Integer nstate) {
        this.nstate = nstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpermission.dtCreateTime
     *
     * @return the value of tbpermission.dtCreateTime
     *
     * @mbggenerated
     */
    public Date getDtcreatetime() {
        return dtcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpermission.dtCreateTime
     *
     * @param dtcreatetime the value for tbpermission.dtCreateTime
     *
     * @mbggenerated
     */
    public void setDtcreatetime(Date dtcreatetime) {
        this.dtcreatetime = dtcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbpermission.dtModifyTime
     *
     * @return the value of tbpermission.dtModifyTime
     *
     * @mbggenerated
     */
    public Date getDtmodifytime() {
        return dtmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbpermission.dtModifyTime
     *
     * @param dtmodifytime the value for tbpermission.dtModifyTime
     *
     * @mbggenerated
     */
    public void setDtmodifytime(Date dtmodifytime) {
        this.dtmodifytime = dtmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbpermission
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lid=").append(lid);
        sb.append(", strpermission=").append(strpermission);
        sb.append(", strdescription=").append(strdescription);
        sb.append(", nstate=").append(nstate);
        sb.append(", dtcreatetime=").append(dtcreatetime);
        sb.append(", dtmodifytime=").append(dtmodifytime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}