package com.vmax.entity;

import java.io.Serializable;
import java.util.Date;

public class Tbrolepermission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrolepermission.lId
     *
     * @mbggenerated
     */
    private Long lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrolepermission.lPermissionId
     *
     * @mbggenerated
     */
    private Long lpermissionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrolepermission.lRoleId
     *
     * @mbggenerated
     */
    private Long lroleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrolepermission.strDescription
     *
     * @mbggenerated
     */
    private String strdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrolepermission.nState
     *
     * @mbggenerated
     */
    private Integer nstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrolepermission.dtCreateTime
     *
     * @mbggenerated
     */
    private Date dtcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrolepermission.dtModifyTime
     *
     * @mbggenerated
     */
    private Date dtmodifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbrolepermission
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrolepermission.lId
     *
     * @return the value of tbrolepermission.lId
     *
     * @mbggenerated
     */
    public Long getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrolepermission.lId
     *
     * @param lid the value for tbrolepermission.lId
     *
     * @mbggenerated
     */
    public void setLid(Long lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrolepermission.lPermissionId
     *
     * @return the value of tbrolepermission.lPermissionId
     *
     * @mbggenerated
     */
    public Long getLpermissionid() {
        return lpermissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrolepermission.lPermissionId
     *
     * @param lpermissionid the value for tbrolepermission.lPermissionId
     *
     * @mbggenerated
     */
    public void setLpermissionid(Long lpermissionid) {
        this.lpermissionid = lpermissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrolepermission.lRoleId
     *
     * @return the value of tbrolepermission.lRoleId
     *
     * @mbggenerated
     */
    public Long getLroleid() {
        return lroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrolepermission.lRoleId
     *
     * @param lroleid the value for tbrolepermission.lRoleId
     *
     * @mbggenerated
     */
    public void setLroleid(Long lroleid) {
        this.lroleid = lroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrolepermission.strDescription
     *
     * @return the value of tbrolepermission.strDescription
     *
     * @mbggenerated
     */
    public String getStrdescription() {
        return strdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrolepermission.strDescription
     *
     * @param strdescription the value for tbrolepermission.strDescription
     *
     * @mbggenerated
     */
    public void setStrdescription(String strdescription) {
        this.strdescription = strdescription == null ? null : strdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrolepermission.nState
     *
     * @return the value of tbrolepermission.nState
     *
     * @mbggenerated
     */
    public Integer getNstate() {
        return nstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrolepermission.nState
     *
     * @param nstate the value for tbrolepermission.nState
     *
     * @mbggenerated
     */
    public void setNstate(Integer nstate) {
        this.nstate = nstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrolepermission.dtCreateTime
     *
     * @return the value of tbrolepermission.dtCreateTime
     *
     * @mbggenerated
     */
    public Date getDtcreatetime() {
        return dtcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrolepermission.dtCreateTime
     *
     * @param dtcreatetime the value for tbrolepermission.dtCreateTime
     *
     * @mbggenerated
     */
    public void setDtcreatetime(Date dtcreatetime) {
        this.dtcreatetime = dtcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrolepermission.dtModifyTime
     *
     * @return the value of tbrolepermission.dtModifyTime
     *
     * @mbggenerated
     */
    public Date getDtmodifytime() {
        return dtmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrolepermission.dtModifyTime
     *
     * @param dtmodifytime the value for tbrolepermission.dtModifyTime
     *
     * @mbggenerated
     */
    public void setDtmodifytime(Date dtmodifytime) {
        this.dtmodifytime = dtmodifytime;
    }

    public Tbrolepermission(Long lpermissionid, Long lroleid, String strdescription, Integer nstate, Date dtcreatetime, Date dtmodifytime) {
        this.lpermissionid = lpermissionid;
        this.lroleid = lroleid;
        this.strdescription = strdescription;
        this.nstate = nstate;
        this.dtcreatetime = dtcreatetime;
        this.dtmodifytime = dtmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrolepermission
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lid=").append(lid);
        sb.append(", lpermissionid=").append(lpermissionid);
        sb.append(", lroleid=").append(lroleid);
        sb.append(", strdescription=").append(strdescription);
        sb.append(", nstate=").append(nstate);
        sb.append(", dtcreatetime=").append(dtcreatetime);
        sb.append(", dtmodifytime=").append(dtmodifytime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}