package com.vmax.entity;

import java.io.Serializable;
import java.util.Date;

public class Tbrole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrole.lId
     *
     * @mbggenerated
     */
    private Long lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrole.strRole
     *
     * @mbggenerated
     */
    private String strrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrole.strDescription
     *
     * @mbggenerated
     */
    private String strdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrole.nState
     *
     * @mbggenerated
     */
    private Integer nstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrole.dtCreateTime
     *
     * @mbggenerated
     */
    private Date dtcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbrole.dtModifyTime
     *
     * @mbggenerated
     */
    private Date dtmodifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbrole
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrole.lId
     *
     * @return the value of tbrole.lId
     *
     * @mbggenerated
     */
    public Long getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrole.lId
     *
     * @param lid the value for tbrole.lId
     *
     * @mbggenerated
     */
    public void setLid(Long lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrole.strRole
     *
     * @return the value of tbrole.strRole
     *
     * @mbggenerated
     */
    public String getStrrole() {
        return strrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrole.strRole
     *
     * @param strrole the value for tbrole.strRole
     *
     * @mbggenerated
     */
    public void setStrrole(String strrole) {
        this.strrole = strrole == null ? null : strrole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrole.strDescription
     *
     * @return the value of tbrole.strDescription
     *
     * @mbggenerated
     */
    public String getStrdescription() {
        return strdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrole.strDescription
     *
     * @param strdescription the value for tbrole.strDescription
     *
     * @mbggenerated
     */
    public void setStrdescription(String strdescription) {
        this.strdescription = strdescription == null ? null : strdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrole.nState
     *
     * @return the value of tbrole.nState
     *
     * @mbggenerated
     */
    public Integer getNstate() {
        return nstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrole.nState
     *
     * @param nstate the value for tbrole.nState
     *
     * @mbggenerated
     */
    public void setNstate(Integer nstate) {
        this.nstate = nstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrole.dtCreateTime
     *
     * @return the value of tbrole.dtCreateTime
     *
     * @mbggenerated
     */
    public Date getDtcreatetime() {
        return dtcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrole.dtCreateTime
     *
     * @param dtcreatetime the value for tbrole.dtCreateTime
     *
     * @mbggenerated
     */
    public void setDtcreatetime(Date dtcreatetime) {
        this.dtcreatetime = dtcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbrole.dtModifyTime
     *
     * @return the value of tbrole.dtModifyTime
     *
     * @mbggenerated
     */
    public Date getDtmodifytime() {
        return dtmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbrole.dtModifyTime
     *
     * @param dtmodifytime the value for tbrole.dtModifyTime
     *
     * @mbggenerated
     */
    public void setDtmodifytime(Date dtmodifytime) {
        this.dtmodifytime = dtmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrole
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lid=").append(lid);
        sb.append(", strrole=").append(strrole);
        sb.append(", strdescription=").append(strdescription);
        sb.append(", nstate=").append(nstate);
        sb.append(", dtcreatetime=").append(dtcreatetime);
        sb.append(", dtmodifytime=").append(dtmodifytime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}