package com.vmax.entity;

import java.io.Serializable;
import java.util.Date;

public class Tbuser implements Serializable {

    private static final long serialVersionUID = 6596814762614120691L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.lId
     *
     * @mbggenerated
     */
    private Long lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.strUserName
     *
     * @mbggenerated
     */
    private String strusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.strPassword
     *
     * @mbggenerated
     */
    private String strpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.strSalt
     *
     * @mbggenerated
     */
    private String strsalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.strPhone
     *
     * @mbggenerated
     */
    private String strphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.strEmali
     *
     * @mbggenerated
     */
    private String stremali;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.nIdentity
     *
     * @mbggenerated
     */
    private Integer nidentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.strLogoUrl
     *
     * @mbggenerated
     */
    private String strlogourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.nState
     *
     * @mbggenerated
     */
    private Integer nstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.dtCreateTime
     *
     * @mbggenerated
     */
    private Date dtcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.dtModifyTime
     *
     * @mbggenerated
     */
    private Date dtmodifytime;

    private int nLock ;

    public int getnLock() {
        return nLock;
    }

    public void setnLock(int nLock) {
        this.nLock = nLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.lId
     *
     * @return the value of tbuser.lId
     *
     * @mbggenerated
     */
    public Long getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.lId
     *
     * @param lid the value for tbuser.lId
     *
     * @mbggenerated
     */
    public void setLid(Long lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.strUserName
     *
     * @return the value of tbuser.strUserName
     *
     * @mbggenerated
     */
    public String getStrusername() {
        return strusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.strUserName
     *
     * @param strusername the value for tbuser.strUserName
     *
     * @mbggenerated
     */
    public void setStrusername(String strusername) {
        this.strusername = strusername == null ? null : strusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.strPassword
     *
     * @return the value of tbuser.strPassword
     *
     * @mbggenerated
     */
    public String getStrpassword() {
        return strpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.strPassword
     *
     * @param strpassword the value for tbuser.strPassword
     *
     * @mbggenerated
     */
    public void setStrpassword(String strpassword) {
        this.strpassword = strpassword == null ? null : strpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.strSalt
     *
     * @return the value of tbuser.strSalt
     *
     * @mbggenerated
     */
    public String getStrsalt() {
        return strsalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.strSalt
     *
     * @param strsalt the value for tbuser.strSalt
     *
     * @mbggenerated
     */
    public void setStrsalt(String strsalt) {
        this.strsalt = strsalt == null ? null : strsalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.strPhone
     *
     * @return the value of tbuser.strPhone
     *
     * @mbggenerated
     */
    public String getStrphone() {
        return strphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.strPhone
     *
     * @param strphone the value for tbuser.strPhone
     *
     * @mbggenerated
     */
    public void setStrphone(String strphone) {
        this.strphone = strphone == null ? null : strphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.strEmali
     *
     * @return the value of tbuser.strEmali
     *
     * @mbggenerated
     */
    public String getStremali() {
        return stremali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.strEmali
     *
     * @param stremali the value for tbuser.strEmali
     *
     * @mbggenerated
     */
    public void setStremali(String stremali) {
        this.stremali = stremali == null ? null : stremali.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.nIdentity
     *
     * @return the value of tbuser.nIdentity
     *
     * @mbggenerated
     */
    public Integer getNidentity() {
        return nidentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.nIdentity
     *
     * @param nidentity the value for tbuser.nIdentity
     *
     * @mbggenerated
     */
    public void setNidentity(Integer nidentity) {
        this.nidentity = nidentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.strLogoUrl
     *
     * @return the value of tbuser.strLogoUrl
     *
     * @mbggenerated
     */
    public String getStrlogourl() {
        return strlogourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.strLogoUrl
     *
     * @param strlogourl the value for tbuser.strLogoUrl
     *
     * @mbggenerated
     */
    public void setStrlogourl(String strlogourl) {
        this.strlogourl = strlogourl == null ? null : strlogourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.nState
     *
     * @return the value of tbuser.nState
     *
     * @mbggenerated
     */
    public Integer getNstate() {
        return nstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.nState
     *
     * @param nstate the value for tbuser.nState
     *
     * @mbggenerated
     */
    public void setNstate(Integer nstate) {
        this.nstate = nstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.dtCreateTime
     *
     * @return the value of tbuser.dtCreateTime
     *
     * @mbggenerated
     */
    public Date getDtcreatetime() {
        return dtcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.dtCreateTime
     *
     * @param dtcreatetime the value for tbuser.dtCreateTime
     *
     * @mbggenerated
     */
    public void setDtcreatetime(Date dtcreatetime) {
        this.dtcreatetime = dtcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.dtModifyTime
     *
     * @return the value of tbuser.dtModifyTime
     *
     * @mbggenerated
     */
    public Date getDtmodifytime() {
        return dtmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.dtModifyTime
     *
     * @param dtmodifytime the value for tbuser.dtModifyTime
     *
     * @mbggenerated
     */
    public void setDtmodifytime(Date dtmodifytime) {
        this.dtmodifytime = dtmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */

    public String getCredentialsSalt(){
        return this.strusername + this.strsalt ;
    }



    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lid=").append(lid);
        sb.append(", strusername=").append(strusername);
        sb.append(", strpassword=").append(strpassword);
        sb.append(", strsalt=").append(strsalt);
        sb.append(", strphone=").append(strphone);
        sb.append(", stremali=").append(stremali);
        sb.append(", nidentity=").append(nidentity);
        sb.append(", strlogourl=").append(strlogourl);
        sb.append(", nstate=").append(nstate);
        sb.append(", dtcreatetime=").append(dtcreatetime);
        sb.append(", dtmodifytime=").append(dtmodifytime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}