package com.vmax.entity;

import java.io.Serializable;
import java.util.Date;

public class Tbuserrole implements Serializable {


    private static final long serialVersionUID = 8525040290016589943L;

    public Tbuserrole( Long luserid, Long lroleid, String strdescription, Integer nstate, Date dtcreatetime, Date dtmodifytime, String strUserName, String strRole) {
        this.luserid = luserid;
        this.lroleid = lroleid;
        this.strdescription = strdescription;
        this.nstate = nstate;
        this.dtcreatetime = dtcreatetime;
        this.strUserName = strUserName;
        this.strRole = strRole;
        this.dtmodifytime = dtmodifytime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserrole.lId
     *
     * @mbggenerated
     */
    private Long lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserrole.lUserId
     *
     * @mbggenerated
     */
    private Long luserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserrole.lRoleId
     *
     * @mbggenerated
     */
    private Long lroleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserrole.strDescription
     *
     * @mbggenerated
     */
    private String strdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserrole.nState
     *
     * @mbggenerated
     */
    private Integer nstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserrole.dtCreateTime
     *
     * @mbggenerated
     */
    private Date dtcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuserrole.dtModifyTime
     *
     * @mbggenerated
     */
    private Date dtmodifytime;

    private String strUserName ;

    private String strRole ;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserrole.lId
     *
     * @return the value of tbuserrole.lId
     *
     * @mbggenerated
     */
    public Long getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserrole.lId
     *
     * @param lid the value for tbuserrole.lId
     *
     * @mbggenerated
     */
    public void setLid(Long lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserrole.lUserId
     *
     * @return the value of tbuserrole.lUserId
     *
     * @mbggenerated
     */
    public Long getLuserid() {
        return luserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserrole.lUserId
     *
     * @param luserid the value for tbuserrole.lUserId
     *
     * @mbggenerated
     */
    public void setLuserid(Long luserid) {
        this.luserid = luserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserrole.lRoleId
     *
     * @return the value of tbuserrole.lRoleId
     *
     * @mbggenerated
     */
    public Long getLroleid() {
        return lroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserrole.lRoleId
     *
     * @param lroleid the value for tbuserrole.lRoleId
     *
     * @mbggenerated
     */
    public void setLroleid(Long lroleid) {
        this.lroleid = lroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserrole.strDescription
     *
     * @return the value of tbuserrole.strDescription
     *
     * @mbggenerated
     */
    public String getStrdescription() {
        return strdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserrole.strDescription
     *
     * @param strdescription the value for tbuserrole.strDescription
     *
     * @mbggenerated
     */
    public void setStrdescription(String strdescription) {
        this.strdescription = strdescription == null ? null : strdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserrole.nState
     *
     * @return the value of tbuserrole.nState
     *
     * @mbggenerated
     */
    public Integer getNstate() {
        return nstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserrole.nState
     *
     * @param nstate the value for tbuserrole.nState
     *
     * @mbggenerated
     */
    public void setNstate(Integer nstate) {
        this.nstate = nstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserrole.dtCreateTime
     *
     * @return the value of tbuserrole.dtCreateTime
     *
     * @mbggenerated
     */
    public Date getDtcreatetime() {
        return dtcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserrole.dtCreateTime
     *
     * @param dtcreatetime the value for tbuserrole.dtCreateTime
     *
     * @mbggenerated
     */
    public void setDtcreatetime(Date dtcreatetime) {
        this.dtcreatetime = dtcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuserrole.dtModifyTime
     *
     * @return the value of tbuserrole.dtModifyTime
     *
     * @mbggenerated
     */
    public Date getDtmodifytime() {
        return dtmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuserrole.dtModifyTime
     *
     * @param dtmodifytime the value for tbuserrole.dtModifyTime
     *
     * @mbggenerated
     */
    public void setDtmodifytime(Date dtmodifytime) {
        this.dtmodifytime = dtmodifytime;
    }

    public String getStrUserName() {
        return strUserName;
    }

    public void setStrUserName(String strUserName) {
        this.strUserName = strUserName;
    }

    public String getStrRole() {
        return strRole;
    }

    public void setStrRole(String strRole) {
        this.strRole = strRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        return "Tbuserrole{" +
                "lid=" + lid +
                ", luserid=" + luserid +
                ", lroleid=" + lroleid +
                ", strdescription='" + strdescription + '\'' +
                ", nstate=" + nstate +
                ", dtcreatetime=" + dtcreatetime +
                ", dtmodifytime=" + dtmodifytime +
                ", strUserName='" + strUserName + '\'' +
                ", strRole='" + strRole + '\'' +
                '}';
    }
}