package com.vmax.mapper;

import com.vmax.entity.Tbuser;
import java.util.List;

public interface TbuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */
    int insert(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */
    Tbuser selectByPrimaryKey(Long lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */
    List<Tbuser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbuser record);

    /**
     * 根据姓名查询用户信息
     * @param strUserName
     * @return
     */
    Tbuser findUserByName(String strUserName);

    /**
     * 根据手机号查询用户信息
     * @param phone
     * @return
     */
    Tbuser findUsrByPhone(String phone) ;
}