package com.vmax.mapper;

import com.vmax.entity.Tbuserrole;
import java.util.List;
import java.util.Set;

public interface TbuserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated
     */
    int insert(Tbuserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated
     */
    Tbuserrole selectByPrimaryKey(Long lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated
     */
    List<Tbuserrole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuserrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbuserrole record);

    /**
     * 根据用户名查询角色名
     * @param strUserName
     * @return
     */
    Set<String> findRolesByUserName(String strUserName) ;
}