package com.vmax.service;

import com.vmax.entity.Tbrolepermission;

import java.util.List;
import java.util.Set;

public interface IRolePermissionService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrolepermission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrolepermission
     *
     * @mbggenerated
     */
    int insert(Tbrolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrolepermission
     *
     * @mbggenerated
     */
    Tbrolepermission selectByPrimaryKey(Long lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrolepermission
     *
     * @mbggenerated
     */
    List<Tbrolepermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbrolepermission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbrolepermission record);

    Set<String> findPermissionsByUserName(String strUserName) ;
}
